spring:
  application:
    name: transaction-service

  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

  datasource:
    url: ${DB_URL_TRANSACTION} #POSTGRESQL DATABASE CONNECTION
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    # Kafka producer configuration
  kafka:
      # Address of the Kafka broker
      bootstrap-servers: localhost:9092

      producer:

        # Convert Java String → Kafka message key
        key-serializer: org.apache.kafka.common.serialization.StringSerializer

        # Convert Java object → JSON
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

        properties:

          # Include Java type information in the JSON message
          # This helps the Kafka consumer know what type of
          # object was sent.
          spring.json.add.type: true

server:
  port: 8082

#Actuator config, health monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: ${JWT_SECRET}